Per-Tile Power Gating
=====================

Per-tile power gating capability allows an idle core to be removed from the power rail to eliminate all power use.  Power gating involves latencies for the power off ramp, power on ramp and a reset flow to restore use of the core.  Therefore power gating utility must be balanced against the power savings.  Agressive use of power gating can result in performance loss.  

_Power gating is the last step in reduction of core idle power.  An idle core uses both dynamic and static power, but dynamic power should be reduced to a minimum before power gating.  An estimate of the difference between peak power and idle power with effective clock gating is 10-20x when DVFS is employed due to voltage scaling.  At the lowest voltage levels static power is minimal, therefore in the presence of DVFS, per-tile power gating may not provide a large power reduction._

Per-complex power gating leverages per-tile power gating when the last core in a complex requests power down.  The core complex contains additional units including the interrupt controller, debug manager, TileLink wrappers and potentially large L3.  Flushing a large L3 can greatly increase latency, so three options are provided.

- Power down the last core and leave the complex powered up and functional
- Power down the last core while logically isolating the complex and L3 in a non-functional, but state retention mode allowing transient power-up periods for cache operations
- Power down the last core, flush the L3 to DRAM and power down the entire core-complex

Power Down Sequence
===================

1. Jump/Interrupt to Core SW power down routine

   Routine is entered either by an external interrupt or timer-based interrupt after the core has been in WFI idle for a period of time.

2. Block incoming TL traffic to core

   Enable TL Slave Bus Blocker via MMIO register
   Bus Blocker denies incoming requests to tile. 

3. Stop all internal core activity

 3a. Flush internal state
     Write out TIM data via SW if present
     Flush cache dirty data via SW if present

 3b. FENCE - (insure cache writes complete, before int disable to catch possible errors?)
     Disable Interrupts
     Disable Prefetchers if possible

4. Wait for TL Slave Bus Blocker done

   Bus Blocker tracks outstanding transactions when enabled and reports done when bus is quiesced via MMIO register. 

   Possible sequence addition to handle core complex power down

 4a. If (Last-core in complex)  - last core can read CEASE state from other cores in TL MMIO regs
        Selections below based on core accessible preset MMIO reg (L3 options: powered-up functional / retention non-functionsl / power-off)
        If (L3 functional) - complex remains powered with cores powered-down for L3 service
        Else Logically isolate core-complex via bus blockers on all core-complex slave TL links
           If (L3 retention) - Non-functional - external agent reduces voltage instead of powering-down completely
              Communicate with external agent to drop voltage on complex - AFTER CEASE and Busses Quiesce
              (requires transient wake-up capability to service external L3 activity)
           Else (L3 power-down)
              Execute L3 flush sequence
              Communicate with external agent to power-down complex - AFTER CEASE and Busses Quiesce
        Wait for slave bus blockers done
           Logically isolate core-complex TL master links (can a core block TL links on the complex and then block them on the core?)
           Logically isolate Core via bus blockers on all Core TL master links via MMIO register
     Else (Not Last-core)
   	Logically isolate Core via bus blockers on all Core TL master links via MMIO register
   	Probes may be received from a coherence manager even after flush
   	Bus Blocker denies outgoing requests from within tile (unexpected after step 3)
   	Bus Blocker denies incoming probes to avoid TL bus deadlocks.  No data is present.

6. Execute CEASE instruction

   CEASE is the last instruction retired by core.
   CEASE must be followed by reset to resume operation.

7. External agent monitors both tile_in_cease signal and Master Bus Blocker quiesent signal.
   If Last-Core
      Monitor Core bus blocker and Complex bus blockers
   Else
      Monitor Core bus blocker 

   Enable isolate gates when all are asserted.
      Isolation logic for a core is inside core-complex       
      Isolation logic for a core complex is outside core-complex in external agent

8. Power can be safely removed from tile. 


   