Per-Tile Power Gating
=====================

A per-tile power gating capability allows an idle core to be removed from the power rail to eliminate all power use.  Power gating involves latencies for the power off ramp, power on ramp and a reset flow to restore use of the core.  Therefore power gating utility must be balanced against the power savings.  Agressive use of power gating can result in performance loss.  

Power gating is the last step in reduction of core idle power.  An idle core uses both dynamic and static power, but dynamic power should be reduced to a minimum before power gating.  An estimate of the difference between peak power and idle power with effective clock gating is 10-20x when DVFS is employed due to voltage scaling.  At the lowest voltage levels static power is minimal, therefore in the presence of DVFS, per-tile power gating may not provide a large power reduction.

Instructions
============

Custom SYSTEM instruction encoding space

Same as custom CSR encoding space, but with funct3=0

CEASE
-----
- opcode 0x30500073 (similar to WFI encoding, but unlike WFI, requires M-mode)
- After retiring CEASE, hart will not retire another instruction until reset
- Asserts external signal after retire indicating that core is ready for power-down.  External control must also wait for bus quiesce. 
- Intended for proposal to RISC-V standard.

CFLUSH.D.L1 (Xsifivecflushdlone0p1)  (not clear what the rev implies) 
-----------------------------------
-opcode 0xFC000073, with optional rs1 field in bits 19:15.
-Only available in M-mode.
-When rs1 = x0, CFLUSH.D.L1 writes back all dirty lines and invalidates all lines in the L1 D$.
-When rs1 != x0, CFLUSH.D.L1 writes back the line if dirty and invalidates the L1 D$ line containing the physical address that is mapped by the virtual address in integer register rs1.
-If the effective privilege mode does not have write permissions to the address in rs1, then a store access or store page-fault exception is raised.
-If the address in rs1 is in an uncacheable region with write permissions, the instruction has no effect but raises no exceptions.

-Note that if the PMP scheme write-protects only part of a cache line, then using a value for rs1 in the write-protected region will cause an exception, whereas using a value for rs1 in the write-permitted region will write back the entire cache line.

-Implemented as state machine in L1 D$. Might not be provided on systems with a coherence hub or L2$ that have a memory-mapped control port that can generate cache probes having the same effect.

-Some implementations might only support the per-address variant, in which case they must raise an illegal-instruction exception when rs1 is x0. Other implementations might only support the full cache-flush variant, in which case when rs1 != x0, either an illegal-instruction exception will be raised, or the entire cache will be flushed.

Power Down Sequence
===================

Must be executed in Machine mode and not from a remote ITIM/DTIM.

1. Jump/Interrupt to Core SW power down routine

   Routine is entered either by an external interrupt or timer-based interrupt after the core has been in WFI idle for a period of time.

2. Block incoming TL traffic to core

   Enable TL Slave Bus Blocker via MMIO register
   Bus Blocker denies incoming requests to tile. 

3. Stop all internal core activity

 3a. Flush internal state
     Write out TIM data via SW if present
     Flush cache dirty data via SW if present (does this require custom instructions?)

 3b. FENCE - (insure cache writes complete, before int disable to catch possible errors?)
     Disable Interrupts
     Disable Prefetchers if possible

4. Wait for TL Slave Bus Blocker done

   Bus Blocker tracks outstanding transactions when enabled and reports done when bus is quiesced via MMIO register. 

5. Block outgoing and probe activity

   Enable TL master Bus Blocker via MMIO register
   Probes may be possible to a coherent cache even after flush depending on coherence manager.
   Bus Blocker denies outgoing requests from within tile (unexpected after step 3)
   Bus Blocker denies incoming probes to avoid TL bus deadlocks.  No data is present.

6. Execute CEASE instruction

   CEASE is the last instruction retired by core.
   CEASE must be followed by reset to resume operation.

7. External agent monitors both tile_in_cease signal and Master Bus Blocker quiesent signal.

   Enable isolate gates when both are asserted.

8. Power can be safely removed from tile. 


   