Per-Tile Power Gating
=====================

A per-tile power gating capability allows an idle core to be removed from the power rail to eliminate all power use.  Power gating involves latencies for the power off ramp, power on ramp and a reset flow to restore use of the core.  Therefore power gating utility must be balanced against the power savings.  Agressive use of power gating can result in performance loss.  

Power gating is the last step in reduction of core idle power.  An idle core uses both dynamic and static power, but dynamic power should be reduced to a minimum before power gating.  An estimate of the difference between peak power and idle power is 10-20x with DVFS due to the voltage scaling.  At the lowest voltage levels, with effective clock gating, dynamic power should be very low leaving static power which is also low due to voltage.  Therefore in the presence of DVFS, per-tile power gating may not provide a large power reduction.

Power Down Sequence
===================

1. Jump/Interrupt to Core SW power down routine

   Routine is entered either by an external interrupt or timer-based interrupt after the core has been in WFI idle for a period of time.

2. Block incoming TL traffic to core

   Enable TL Slave Bus Blocker via MMIO register
   Bus Blocker denies incoming requests to tile. 

3. Stop all internal core activity

 3a. Flush internal state
     Write out TIM data via SW if present
     Flush cache dirty data via SW if present

 3a. FENCE - (unclear why this is needed in Andrew's flow)
     Disable Interrupts
     Disable Prefetchers if possible

4. Wait for TL Slave Bus Blocker done

   Bus Blocker tracks outstanding transactions when enabled and reports done when bus is quiesced via MMIO register. 

5. Block outgoing and probe activity

   Enable TL master Bus Blocker via MMIO register
   Probes may be possible to a coherent cache even after flush depending on coherence manager.
   Bus Blocker denies outgoing requests from within tile (unexpected after step 3)
   Bus Blocker denies incoming probes to avoid TL bus deadlocks.  No data is present.

6. Execute CEASE instruction

   CEASE is the last instruction retired by core.
   CEASE must be followed by reset to resume operation.

7. External agent monitors both tile_in_cease signal and Master Bus Blocker quiesent signal.

   Enable isolate gates when both are asserted.

8. Power can be safely removed from tile. 


   