Power Gating
============

Per-tile power gating capability allows an idle core to be removed from the power rail to eliminate all power use.  Power gating involves latencies for the power off ramp, power on ramp and a reset flow to restore use of the core.  Therefore power gating utility must be balanced against the power savings.  Agressive use of power gating can result in performance loss.  

_Power gating is the last step in reduction of core idle power.  An idle core uses both dynamic and static power, but dynamic power should be reduced to a minimum before power gating.  An estimate of the difference between peak power and idle power with effective clock gating is 10-20x when DVFS is employed due to voltage scaling.  At the lowest voltage levels static power is minimal, therefore in the presence of DVFS, per-tile power gating may not provide a large power reduction._

Per-complex power gating leverages per-tile power gating when the last core in a complex requests power down.  The core complex contains additional units including the interrupt controller, debug manager, TileLink wrappers and potentially large L3.  Flushing a large L3 can greatly increase latency, so three options are provided.

- Power down the last core and leave the complex powered up and functional
- Power down the last core while logically isolating the complex and L3 in a non-functional, but state retention mode allowing transient power-up periods for cache operations
- Power down the last core, flush the L3 to DRAM and power down the entire core-complex

Instructions
============

Custom SYSTEM instruction encoding space

Same as custom CSR encoding space, but with funct3=0

CEASE
-----
- opcode 0x30500073 (similar to WFI encoding, but unlike WFI, requires M-mode)
- After retiring CEASE, hart will not retire another instruction until reset
- Asserts external signal after retire indicating that core is ready for power-down.  External control must also wait for bus quiesce. 
- Intended for proposal to RISC-V standard.

CFLUSH.D.L1 (Xsifivecflushdlone0p1) 
-----------------------------------

- opcode 0xFC000073, with optional rs1 field in bits 19:15.
- Only available in M-mode.
- When rs1 = x0, CFLUSH.D.L1 writes back all dirty lines and invalidates all lines in the L1 D$.
- When rs1 != x0, CFLUSH.D.L1 writes back the line if dirty and invalidates the L1 D$ line containing the physical address that is mapped by the virtual address in integer register rs1.
- If the effective privilege mode does not have write permissions to the address in rs1, then a store access or store page-fault exception is raised.
- If the address in rs1 is in an uncacheable region with write permissions, the instruction has no effect but raises no exceptions.

- Note that if the PMP scheme write-protects only part of a cache line, then using a value for rs1 in the write-protected region will cause an exception, whereas using a value for rs1 in the write-permitted region will write back the entire cache line.

- Implemented as state machine in L1 D$. Might not be provided on systems with a coherence hub or L2$ that have a memory-mapped control port that can generate cache probes having the same effect.

- Some implementations might only support the per-address variant, in which case they must raise an illegal-instruction exception when rs1 is x0. Other implementations might only support the full cache-flush variant, in which case when rs1 != x0, either an illegal-instruction exception will be raised, or the entire cache will be flushed.

Power Down Sequence
===================

Must be executed in Machine mode and not from a remote ITIM/DTIM. 

1. Jump/Interrupt to Core SW power down routine

   Routine is entered either by an external interrupt or timer-based interrupt after the core has been in WFI idle for a period of time.

2. Block incoming TL traffic to core

   Enable TL Slave Bus Blocker via MMIO register
   Bus Blocker denies incoming requests to tile. 

3. Stop all internal core activity

 3a. Flush internal state
     Write out TIM data via SW if present
     Flush cache dirty data via SW if present (does this require custom instructions?)

 3b. FENCE - (insure cache writes complete, before int disable to catch possible errors?)
     Disable Interrupts
     Disable Prefetchers if possible

4. Wait for TL Slave Bus Blocker done

   Bus Blocker tracks outstanding transactions when enabled and reports done when bus is quiesced via MMIO register. 

   *Option to handle core complex power down*

 4a. If (Last-core in complex)  - last core can read CEASE state from other cores in TL MMIO regs
        Selections below based on core accessible preset MMIO reg (L3 options: powered-up functional / retention non-functionsl / power-off)
        If (L3 functional) - complex remains powered with cores powered-down for L3 service
        Else Logically isolate core-complex via bus blockers on all core-complex slave TL links
           If (L3 retention) - Non-functional - external agent reduces voltage instead of powering-down completely
              Communicate with external agent to drop voltage on complex - AFTER CEASE and Busses Quiesce
              (requires transient wake-up capability to service external L3 activity)
           Else (L3 power-down)
              Execute L3 flush sequence
              Communicate with external agent to power-down complex - AFTER CEASE and Busses Quiesce
           Wait for core-complex slave bus blockers done
           Logically isolate Core-Complex TL master links (can a core block TL links on the complex and then block them on the core?)
        Logically isolate Core TL master links 
     Else (Not Last-core)
        Logically isolate Core TL master links 
        Probes may be received from a coherence manager even after flush
        Bus Blocker denies outgoing requests from within tile (unexpected after step 3)
        Bus Blocker denies incoming probes to avoid TL bus deadlocks.  No data is present.

6. Execute CEASE instruction

   CEASE is the last instruction retired by core.
   CEASE must be followed by reset to resume operation.

7. External agent monitors both tile_in_cease signal and Master Bus Blocker quiesent signal.
   If Last-Core
      Monitor Core bus blocker and Complex bus blockers
   Else
      Monitor Core bus blocker 

   Enable isolate gates when all are asserted.
      Isolation logic for a core is inside core-complex       
      Isolation logic for a core complex is outside core-complex in external agent

8. Power can be safely removed from tile. 


   